name: nutifitapplications
description: A personalized workout app

publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  syncfusion_flutter_charts: ^26.2.7
  firebase_core: ^2.15.1
  firebase_auth: ^4.8.2
  video_player: ^2.2.18
  url_launcher: ^6.0.9
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.13  # Add the latest version
  clipboard: ^0.1.3  # Add this to your pubspec.yaml
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/pic_1.jpg
    - assets/images/nutrition.jpg
    - assets/images/9-move-body-weight-workout.jpg
    - assets/images/pic_2_4.jpg
    - assets/images/intro_pic.png
    - assets/images/profile.png
